import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AiOutlineShoppingCart } from "react-icons/ai";
import { BsBookmark } from "react-icons/bs";

import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <a href="https://web.furrl.in/wishlist">
              <BsBookmark className="icon" />
              <a href="https://web.furrl.in/cart">
                {" "}
                <AiOutlineShoppingCart className="icon" />
              </a>
            </a>
            {/* <FiShare className="icon" /> */}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
